### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by TheMarstonConnell** [JackalLabs/jackal.js#15]
# v3
Bidirectionally reliant on https://github.com/JackalLabs/canine-chain/issues/365 
Bidirectionally reliant on https://github.com/JackalLabs/jackal.js-protos/issues/15

For the Jackal Protocol v4 upgrade, the logic surrounding uploading files has changed enormously. Thus making Jackal.js v1 & v2 incompatible with the chain. During the chain upgrade, all web-apps using Jackal.js must update to Jackal.js v3.x.x in order to continue using the Jackal Protocol.

```[tasklist]
### Success Criteria
- [x] Reverse post file order
- [x] Merkle file before posting to chain to get merkle root (now required by PostFile)
```

**Comment by karnthis** [comment]
completed with publish of v3

https://github.com/JackalLabs/jackal.js/releases/tag/v3.0.0
