### ISSUE TITLE
`readFileTreeEntry` missing exception & `downloadFolder` using the wrong FileTree read method

### ISSUE THREAD

**Issue by ahm23** [JackalLabs/jackal.js#17]
When `readFileTreeEntry` fails to get FileTree data, it returns an [empty object](https://github.com/JackalLabs/jackal.js/blob/cad2e8ffddec2df9a6efed04145a4e16523a6173/src/utils/compression.ts#L158) instead of raising an exception.

`downloadFolder` from `FileIo` will process this empty object and generate an empty folder record instead of propagating an error. For any application using this function, there is no way to differentiate whether an error has occurred or if the folder is simply empty.

On a side note, there is no catch handler attached to `getFileTreeData` in `readFileTreeEntry` but there is one in `readFileTreeFolder`. I believe `readFileTreeFolder` is what's supposed to be used in `downloadFolder`? Although the `.catch()` handler doesn't actually do anything because of the way things are in jackal.js-protos, the function throws an error instead of returning a blank object when the success indicator is false.

**Comment by karnthis** [comment]
Excellent points, and you are correct. These are a legacy of how Jackal.js was designed originally, and never got cleaned up. The move to v4 has resulted in a complete rewrite so a lot of these internals don't even exist now. You can see a wip in the v3 branch!
