### ISSUE TITLE
Video uploads fail unnecessarily depending on the video codec

### ISSUE THREAD

**Issue by ahm23** [JackalLabs/jackal.js#24]
If the file being uploaded is a video type, `processPrivate` will try to create a thumbnail to be able to display a preview frame of the video on a file browser UI.
https://github.com/JackalLabs/jackal.js/blob/d07f30474f4836a75ff6ea8a416d91ae21f71363/src/classes/storageHandler.ts#L1909
`maybeMakeThumbnail` uses the `extractThumbnailFromVideo` function to create a thumbnail from a video. The video is loaded into a video element (which uses MediaSource Extension) which is then used to extract a frame from the video. There are many codecs which MSE isn't capable of handling, though for the most common codecs it is fine. The issue is, if someone tries to upload a video file with an MSE-incompatible codec but it works offline on their PC, `extractThumbnailFromVideo` throws an exception which prevents the file from getting processed and staged in an upload.
https://github.com/JackalLabs/jackal.js/blob/d07f30474f4836a75ff6ea8a416d91ae21f71363/src/utils/converters.ts#L290

**Comment by karnthis** [comment]
this should be a pretty minor fix. I'll look into it once we have sharing wrapped.

**Comment by TheMarstonConnell** [comment]
Noticed this as well with some images such as iPhone images

**Comment by karnthis** [comment]
resolved in v3.5.0
